### ISSUE TITLE
Github Permissions

### ISSUE THREAD

**Issue by iamnathanwindsor** [MenloOne/townhall#4]
Hi Guys, when trying to run:

`git clone git@github.com:vulcanize/message_board_reactjs.git
`

I get:
Cloning into 'message_board_reactjs'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by iamnathanwindsor** [comment]
Any update on this?

**Comment by matthewnolan** [comment]
resolved

**Comment by iamnathanwindsor** [comment]
Sorry, I'm still pulling the error on my side. Any ideas why?
